version: '3'
services:
  ssh-server:
    container_name: shared_ssh
    build:
      context: .
      args:
        - SSH_USER=${SSH_USER}
        - SSH_PASSWORD=${SSH_PASSWORD}
        - SSH_PORT=${SSH_PORT}
    ports:
      - "${HOST_PORT}:${SSH_PORT}"
    volumes:
      - ${SHARED_DIR}:/shared
    env_file:
      - .env
    restart: unless-stopped